server:
  port: 9090
zk:
  address: 47.102.221.182:4181
  connectTimeOut: 20000
  sessionTimeOut: 10000
  registryPath: "/defaultRegistry"
rpc:
  client:
    routeStrategy: Polling
    serializeType: ProtoStuff